<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="colours.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_radius" value="0.07"/>
    <xacro:property name="chassis_height" value="0.115"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="caster_wheel_radius" value="0.0175"/>
    <xacro:property name="wheel_offset" value="${chassis_radius-wheel_width/2+0.005}"/>

    <link name="base_link">
    </link>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.5" radius="${chassis_radius}" length="${chassis_height}">
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${wheel_radius}" length="${wheel_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${wheel_radius}" length="${wheel_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <link name="top_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    <link name="bottom_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${wheel_offset} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <joint name="top_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="top_caster_wheel"/>
        <origin xyz="0.05 0 -${0.035/2}" rpy="0 0 0"/>
    </joint>
    <joint name="bottom_caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="bottom_caster_wheel"/>
        <origin xyz="-0.05 0 -${0.035/2}" rpy="0 0 0"/>
    </joint>

</robot>